### ISSUE TITLE
Poem 68: image missing from AE headnote in comparison view

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#281]
In the AE headnote, an image is embedded. It shows up in the single-version view, but not in comparison view.

**Comment by emwitty** [comment]
Poem 68 is encoded with `milestone` markers for the labels. Changing these to `label` tags as a first step.

**Comment by sergei-kalugin** [comment]
`tei:label` it is

**Comment by sergei-kalugin** [comment]
I'm not against changing `milestone`s to `label`s. We need to keep track of the poems with these elements though in order to keep the usage consistent.

The list so far: [P001](https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.com/poems/ee/the-eclipse/), [P056](https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.com/poems/ee/a-dialogue-between-two-sisters-virgins-bewailing-their-solitary-life/), [P068](https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.com/poems/ee/come-my-dear-children-emblem-2/)...

**Comment by emwitty** [comment]
This message from 2014 probably characterizes better than I can express it, some of the rationale I about the use of milestone vs. label: 
https://listserv.brown.edu/cgi-bin/wa?A2=ind1401&L=TEI-L&P=68937

"The marginal numbers ... extrinsic, marking divisions in the text and indicating the text's progress according to a standard reference system. We would definitely tag
these as `<milestone>`s"
e.g. https://textcreationpartnership.org/docs/pix/structs/mile-verse.gif

If "interpret[ing] the marginalia as somehow heading the accompanying
text, rather than standing outside it and commenting on it, and
therefore of being tagged as `<label>`"
e.g. https://textcreationpartnership.org/docs/pix/structs/marg-label.gif

**Comment by LeahKnight** [comment]
Matt, Sergei: we've resolved this by moving the image from the headnote to a Curation.
