### ISSUE TITLE
C76: Push to Preview

### ISSUE THREAD

**Issue by k-poland** [MADStudioNU/the-pulter-project#343]

**Comment by sergei-kalugin** [comment]
@LeahKnight, @k-poland, @katgaro: since there're no editions of this poem published yet, here are the links to standalone versions of the curations:

**A creature called a cannibal?**
https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/curations/c76-a-creature-called-a-cannibal.html

**Indulgent Parenting**
https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/curations/c76-indulgent-parenting.html

Also, as discussed with Elizabeth, she prefers to go by "Elizabeth Kolkovich" in TPP land. I updated the header accordingly.
