### ISSUE TITLE
Poem 68: Publish T&EE

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#423]
We need to wait on the AE until Sarah and Millie proofread it, @sergei-kalugin - the rest looks good!

**Comment by wendywall** [comment]
I think that we should assign the proofing to Sam, Katie or Katrina, since Millie and Sarah have failed to respond.
Wendy

Wendy Wall
Co-director with Leah Knight
The Pulter Project: Poet in the Making<http://pulterproject.northwestern.edu/>
(Follow: @PulterProject)

Director, Kaplan Institute for the Humanities
Avalon Foundation Professor of the Humanities
Charles Deering McCormick Professor of Teaching Excellence

**Comment by LeahKnight** [comment]
@sergei-kalugin Poem 68 can be published now; Katrina has proofed all versions. Thanks!
