### ISSUE TITLE
Poem 65 (AED): line 10, close gap between — and "is burned" (remove space)

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#540]
I think the issue here stems from the <seg> tag that we use to wrap lemma and include notes. The line looks fine in normal view because of the box around it, but in comparison view, there's no box, so it seems like there's a space between — and "is burned". I'm not sure how to fix this...

**Comment by emwitty** [comment]
In the processing of the TEI document through XSLT, ambiguous whitespace is introduced in the resulting HTML, due to the indentation for readability. Adding the directive `<xsl:strip-space elements="*" />` to the XSLT would forcibly fix this problem but would introduce numerous other formatting errors elsewhere since any two consecutive `tei:seg`s having notes would be mashed together.  This is a tough nut.

**Comment by emwitty** [comment]
I think we can just use the same hack Sergei uses in the other view, included in above commit for VM, provided the only formatting anomaly is two consecutive 'tei:seg's with 'tei:note's inside being mashed up. Should probably look over all the poems in VM before pushing live.

**Comment by emwitty** [comment]
proposed fix deployed to preview site for testing
