### ISSUE TITLE
Consistency of Cur/Exp citation headers

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#604]
Looks like we have a different approach going with the citation headers.

The convention used to be to use italics for the title and keep the short ones on the same line as the author's name:
![Screen Shot 2021-05-14 at 11 41 38 AM](https://user-images.githubusercontent.com/2558705/118302108-72987980-b4a9-11eb-99d0-b3c2c8a9c31d.png)

and for the long ones to begin on a new line
![Screen Shot 2021-05-14 at 11 41 56 AM](https://user-images.githubusercontent.com/2558705/118302106-71ffe300-b4a9-11eb-88a5-c65b47e81d06.png)

But recently I've been seeing a ton of quotation marks:
![Screen Shot 2021-05-14 at 11 45 01 AM](https://user-images.githubusercontent.com/2558705/118302442-d622a700-b4a9-11eb-9622-593ded4ac952.png)

IMHO, we should stick to one style.

@LeahKnight, can you please weigh in?

**Comment by LeahKnight** [comment]
@sergei-kalugin Most style guides in our discipline (MLA, Chicago, Oxford) advise using italics on the titles of complete works (_Leah Knight: The Lost Years_) and quotation marks around parts, like chapters in a book (Chapter 1, "'Nap When the Baby Naps' Is Cruel Advice") or individual poems in a collection ("Because the Baby Never Naps"). When we first published Curations, I don't think we thought to observe this distinction; thanks for pointing it out, Sergei. We should now thoroughly edit the site with this in mind. @katgaro would you mind putting this on your list--and updating the Curations/Explorations guide to clarify the matter?

**Comment by katgaro** [comment]
@sergei-kalugin @LeahKnight Got it. I'll add this info to the appropriate encoding guide.

**Comment by LeahKnight** [comment]
Thanks @kat I'll assume you've done so and close this issue.
