### ISSUE TITLE
Publish A012 and C012s

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#663]

**Comment by sergei-kalugin** [comment]
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ee/the-garden-or-the-contention-of-flowers/#ctxs

**Comment by sergei-kalugin** [comment]
I will have to take a look at this before pushing to prod, if you guys don't mind.

**Comment by lhn4977** [comment]
Please do. Thank you Sergei!

**Comment by sergei-kalugin** [comment]
### Remaining issues

- [ ] poem file line 1256 — convert to citation block
- [ ] fix double quotation marks throughout the poem

**Comment by LeahKnight** [comment]
@lhn4977

**Comment by lhn4977** [comment]
@sergei-kalugin i believe i fixed all the items on the poem list, but please feel free to check again! thanks, Sergei!

**Comment by sergei-kalugin** [comment]
@lhn4977, @LeahKnight 

The final stretch, guys. Sorry for the hold-up. The poem looks good but the following needs to checked and corrected in the curations:

- [ ] Make sure that in the text the correct apostrophe character (`’`) is used and _not_ a single quotation mark (`'`);
- [ ] Make sure correct characters for the double quotation marks are used (in the text, not in the mark-up) (`“”`) and _not_ (`"`);
- [ ] Make sure there are no double spaces in the text;
- [ ] Make sure the correct ellipsis character is used (`…`) and _not_ three consecutive dots (`...`);
- [ ] Make sure the correct characters are used for em dashes (`—`), en dashes (`–`) and _not_ (`-`) or (`--`);
- [ ] The Curation _Picturing Pulter’s Flowers_ appears to be titled _Images of Flowers_. Which one is the correct title?
- [ ] Make sure proper heading tags are used instead of paragraphs (`<p>`) where needed. We have two available for curations/explorations: `<h3>` and `<h4>`.

**Comment by lhn4977** [comment]
@sergei-kalugin the Curation title should be _Picturing Pulter's Flowers_.

**Comment by lhn4977** [comment]
@sergei-kalugin Okay, I think I've made all/most of the revisions. Could you please take a look and let me know if there are other things you'd like me to address? Thanks, Sergei!

**Comment by sergei-kalugin** [comment]
OK, @lhn4977 & @LeahKnight, I think this is good to go. Green light?

**Comment by lhn4977** [comment]
looks good to me!

**Comment by LeahKnight** [comment]
Close, but not quite! please see my email @sergei-kalugin and @lhn4977

**Comment by lhn4977** [comment]
@sergei-kalugin I went through your footnote formatting in the "Expanding" Curation and replicated that for all the footnote hyperlinks in the "Parliament" Curation. Hopefully they're done correctly, but please double-check!
@LeahKnight everything else has been fixed!

**Comment by sergei-kalugin** [comment]
Got you. I'll check your work, @lhn4977!

**Comment by sergei-kalugin** [comment]
@lhn4977: the footnotes in _Parliaments of Flowers_ looks great!

**Comment by sergei-kalugin** [comment]
I'm also going through curations and making some markup/styling changes in order to make it more semantic. @LeahKnight, let me know if this makes sense.

Before:
![Screen Shot 2021-06-17 at 11 28 14](https://user-images.githubusercontent.com/2558705/122437405-4b791000-cf5f-11eb-8481-bb7f63b03843.png)

After:
![Screen Shot 2021-06-17 at 11 25 59](https://user-images.githubusercontent.com/2558705/122437426-503dc400-cf5f-11eb-87d2-331298705b92.png)

**Comment by LeahKnight** [comment]
@sergei-kalugin Thanks for this good idea! 

@sam, would you please update the encoding guide to keep track of this change?

**Comment by LeahKnight** [comment]
I believe these are ready to publish! Thank you, @sergei-kalugin and @lhn4977 , for pushing through.

**Comment by sergei-kalugin** [comment]
@LeahKnight, @lhn4977: this has been published to production

https://pulterproject.northwestern.edu/poems/ae/the-garden-or-the-contention-of-flowers/

**Comment by lhn4977** [comment]
Sergei,

Thank you so much!!! You're our hero!

Sam

*Sam Nguyen *(she/her/hers)
Northwestern University '21
English Literature Major
+1 (224) 999 5703
